/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.68).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ActivityDTO;
import io.swagger.model.CreateActivityRequest;
import org.threeten.bp.LocalDate;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2025-05-15T10:20:28.371833724Z[GMT]")
@Validated
public interface ActivitiesApi {

    @Operation(summary = "Get activities between dates", description = "", tags={ "Activities" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Activities between dates", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ActivityDTO.class)))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized") })
    @RequestMapping(value = "/activities/between",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<ActivityDTO>> activitiesBetweenGet(@NotNull @Parameter(in = ParameterIn.QUERY, description = "" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "start", required = true) LocalDate start
, @NotNull @Parameter(in = ParameterIn.QUERY, description = "" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "end", required = true) LocalDate end
);


    @Operation(summary = "Get activities by category", description = "", tags={ "Activities" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Activities in category", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ActivityDTO.class)))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized") })
    @RequestMapping(value = "/activities/category/{categoryId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<ActivityDTO>> activitiesCategoryCategoryIdGet(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("categoryId") Integer categoryId
);


    @Operation(summary = "Create a new activity", description = "", tags={ "Activities" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Activity created", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ActivityDTO.class))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized") })
    @RequestMapping(value = "/activities/create",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ActivityDTO> activitiesCreatePost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody CreateActivityRequest body
);


    @Operation(summary = "Delete an activity", description = "", tags={ "Activities" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Activity deleted"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized"),
        
        @ApiResponse(responseCode = "404", description = "Activity not found") })
    @RequestMapping(value = "/activities/delete/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> activitiesDeleteIdDelete(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("id") Integer id
);


    @Operation(summary = "Edit an activity", description = "", tags={ "Activities" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Activity updated"),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized"),
        
        @ApiResponse(responseCode = "404", description = "Activity not found") })
    @RequestMapping(value = "/activities/edit/{id}",
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Void> activitiesEditIdPut(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("id") Integer id
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody CreateActivityRequest body
);


    @Operation(summary = "Get future activities", description = "", tags={ "Activities" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "List of future activities", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ActivityDTO.class)))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized") })
    @RequestMapping(value = "/activities/future",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<ActivityDTO>> activitiesFutureGet();


    @Operation(summary = "Get ongoing activities", description = "", tags={ "Activities" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "List of ongoing activities", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ActivityDTO.class)))),
        
        @ApiResponse(responseCode = "401", description = "Unauthorized") })
    @RequestMapping(value = "/activities/ongoing",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<ActivityDTO>> activitiesOngoingGet();

}

